"""Session report — plain-English HTML that a non-coder can read to verify what Claude did.

This is the trust layer. Claude can't mark its own work done. This report runs
every command, checks every file, and shows what's real and what's broken.
The user opens it in a browser and sees the truth without reading Python.
"""

from __future__ import annotations

import importlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def generate(repo_root: Path) -> str:
    """Run all health checks and return an HTML report string."""
    repo_root = Path(repo_root).resolve()
    docs_dir = repo_root / "devlead_docs"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    sections: list[str] = []

    sections.append(_check_install(repo_root, docs_dir))
    sections.append(_check_hooks(repo_root))
    sections.append(_check_commands(repo_root))
    sections.append(_check_intake(docs_dir))
    sections.append(_check_audit(docs_dir))
    sections.append(_check_modules(repo_root))
    sections.append(_check_files_changed(repo_root))

    pass_count = sum(s.count('class="pass"') for s in sections)
    fail_count = sum(s.count('class="fail"') for s in sections)
    warn_count = sum(s.count('class="warn"') for s in sections)

    verdict = "ALL CHECKS PASSED" if fail_count == 0 else f"{fail_count} CHECKS FAILED"
    verdict_class = "pass" if fail_count == 0 else "fail"

    body = "\n".join(sections)

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>DevLead Session Report</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; background: #f9fafb; color: #1f2937; line-height: 1.6; }}
h1 {{ color: #2563eb; margin-bottom: 4px; }}
h2 {{ border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-top: 40px; }}
.meta {{ color: #6b7280; font-size: 14px; }}
.verdict {{ font-size: 24px; font-weight: bold; padding: 16px; border-radius: 8px; margin: 20px 0; text-align: center; }}
.verdict.pass {{ background: #d1fae5; color: #059669; }}
.verdict.fail {{ background: #fee2e2; color: #dc2626; }}
table {{ border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 14px; }}
th, td {{ border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }}
th {{ background: #dbeafe; font-weight: 600; }}
.pass {{ color: #059669; font-weight: 600; }}
.fail {{ color: #dc2626; font-weight: 600; }}
.warn {{ color: #d97706; font-weight: 600; }}
.info {{ color: #6b7280; }}
pre {{ background: #f3f4f6; padding: 12px; border-radius: 6px; font-size: 13px; overflow-x: auto; }}
</style></head><body>
<h1>DevLead Session Report</h1>
<p class="meta">Generated: {now}</p>
<p class="meta">Project: {repo_root}</p>

<div class="verdict {verdict_class}">{verdict}</div>
<p>{pass_count} passed, {fail_count} failed, {warn_count} warnings</p>

{body}

<p class="meta" style="margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px;">
This report was generated by <code>devlead report</code>. It runs real checks, not self-reported status.
If Claude says "everything works" but this report shows failures, trust the report.</p>
</body></html>"""


def _check_install(repo_root: Path, docs_dir: Path) -> str:
    rows = []
    expected = [
        "_resume.md", "_scratchpad.md", "_intake_features.md", "_intake_bugs.md",
        "_living_decisions.md", "_living_project.md", "_living_standing_instructions.md",
        "_project_hierarchy.md", "_project_status.md",
        "_aware_features.md", "_aware_design.md",
        "_audit_log.jsonl", "_intake_templates/default.md",
    ]
    for f in expected:
        path = docs_dir / f
        exists = path.exists()
        size = path.stat().st_size if exists else 0
        status = "pass" if exists else "fail"
        label = "EXISTS" if exists else "MISSING"
        note = f"{size} bytes" if exists else "file not found"
        rows.append(f'<tr><td><code>{f}</code></td><td class="{status}">{label}</td><td>{note}</td></tr>')

    claude_md = repo_root / "CLAUDE.md"
    if claude_md.exists():
        has_section = "devlead:claude-md-start" in claude_md.read_text(encoding="utf-8")
        if has_section:
            rows.append('<tr><td><code>CLAUDE.md</code></td><td class="pass">HAS DEVLEAD SECTION</td><td>Auto-generated governance rules present</td></tr>')
        else:
            rows.append('<tr><td><code>CLAUDE.md</code></td><td class="warn">NO DEVLEAD SECTION</td><td>File exists but missing auto-generated section</td></tr>')
    else:
        rows.append('<tr><td><code>CLAUDE.md</code></td><td class="fail">MISSING</td><td>No CLAUDE.md at project root</td></tr>')

    return f"""<h2>1. Installation health</h2>
<p>Does devlead_docs/ have all required files?</p>
<table><thead><tr><th>File</th><th>Status</th><th>Note</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>"""


def _check_hooks(repo_root: Path) -> str:
    settings = repo_root / ".claude" / "settings.json"
    if not settings.exists():
        return """<h2>2. Hook wiring</h2>
<p class="fail">FAIL: .claude/settings.json does not exist. No hooks are active. Claude is completely ungoverned.</p>"""

    data = json.loads(settings.read_text(encoding="utf-8"))
    hooks = data.get("hooks", {})
    rows = []

    for hook_name in ["SessionStart", "PreToolUse"]:
        hook_list = hooks.get(hook_name, [])
        has_devlead = any(
            "devlead gate" in sub.get("command", "")
            for h in hook_list for sub in h.get("hooks", [])
        )
        if has_devlead:
            rows.append(f'<tr><td>{hook_name}</td><td class="pass">WIRED</td><td>devlead gate will fire</td></tr>')
        else:
            rows.append(f'<tr><td>{hook_name}</td><td class="fail">NOT WIRED</td><td>Claude is not governed on this hook</td></tr>')

    return f"""<h2>2. Hook wiring</h2>
<p>Are Claude Code hooks configured to call DevLead?</p>
<table><thead><tr><th>Hook</th><th>Status</th><th>Meaning</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>"""


def _check_commands(repo_root: Path) -> str:
    commands = [
        (["intake"], "List intake entries"),
        (["scratchpad"], "List scratchpad entries"),
        (["focus", "show"], "Show current focus"),
        (["config", "show"], "Show config"),
        (["verify-links"], "Check cross-references"),
        (["audit", "recent", "5"], "Show recent audit events"),
    ]
    rows = []
    for cmd_args, description in commands:
        try:
            result = subprocess.run(
                [sys.executable, "-m", "devlead"] + cmd_args,
                capture_output=True, text=True, timeout=10,
                cwd=str(repo_root),
                env={**__import__("os").environ, "PYTHONPATH": str(repo_root / "src")},
            )
            if result.returncode == 0:
                first_line = (result.stdout.strip().splitlines() or ["(empty output)"])[0][:80]
                rows.append(f'<tr><td><code>devlead {" ".join(cmd_args)}</code></td><td class="pass">OK</td><td>{_esc(first_line)}</td></tr>')
            else:
                err = (result.stderr.strip().splitlines() or ["unknown error"])[0][:80]
                rows.append(f'<tr><td><code>devlead {" ".join(cmd_args)}</code></td><td class="fail">EXIT {result.returncode}</td><td>{_esc(err)}</td></tr>')
        except Exception as e:
            rows.append(f'<tr><td><code>devlead {" ".join(cmd_args)}</code></td><td class="fail">ERROR</td><td>{_esc(str(e)[:80])}</td></tr>')

    return f"""<h2>3. Command health</h2>
<p>Can every DevLead command actually run without crashing?</p>
<table><thead><tr><th>Command</th><th>Status</th><th>Output</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>"""


def _check_intake(docs_dir: Path) -> str:
    try:
        from devlead import intake
        rows = []
        total = 0
        done = 0
        pending = 0
        in_progress = 0
        for f in sorted(docs_dir.glob("_intake_*.md")):
            entries = intake.read(f)
            for e in entries:
                total += 1
                if e.status == "done":
                    done += 1
                elif e.status == "in_progress":
                    in_progress += 1
                else:
                    pending += 1
                status_class = "pass" if e.status == "done" else ("warn" if e.status == "in_progress" else "info")
                rows.append(f'<tr><td>{e.id}</td><td>{_esc(e.title[:60])}</td><td class="{status_class}">{e.status}</td><td>{e.origin}</td></tr>')

        summary = f"{total} entries: {done} done, {in_progress} in progress, {pending} pending"
        return f"""<h2>4. Intake status</h2>
<p>{summary}</p>
<table><thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Origin</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>"""
    except Exception as e:
        return f'<h2>4. Intake status</h2><p class="fail">ERROR reading intake: {_esc(str(e))}</p>'


def _check_audit(docs_dir: Path) -> str:
    log_path = docs_dir / "_audit_log.jsonl"
    if not log_path.exists():
        return '<h2>5. Audit log</h2><p class="fail">_audit_log.jsonl does not exist</p>'
    lines = [l.strip() for l in log_path.read_text(encoding="utf-8").splitlines() if l.strip()]
    if not lines:
        return '<h2>5. Audit log</h2><p class="warn">_audit_log.jsonl is empty (0 events). Either no commands have run through DevLead, or audit wiring is broken.</p>'

    event_counts: dict[str, int] = {}
    for line in lines:
        try:
            ev = json.loads(line)
            event_counts[ev.get("event", "unknown")] = event_counts.get(ev.get("event", "unknown"), 0) + 1
        except json.JSONDecodeError:
            pass

    rows = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in sorted(event_counts.items()))
    return f"""<h2>5. Audit log</h2>
<p>{len(lines)} total events</p>
<table><thead><tr><th>Event type</th><th>Count</th></tr></thead>
<tbody>{rows}</tbody></table>"""


def _check_modules(repo_root: Path) -> str:
    src_dir = repo_root / "src" / "devlead"
    if not src_dir.exists():
        return '<h2>6. Module health</h2><p class="info">No src/devlead/ directory</p>'

    modules = sorted(f.stem for f in src_dir.glob("*.py") if f.stem != "__pycache__")
    rows = []
    for mod_name in modules:
        if mod_name.startswith("__"):
            continue
        try:
            importlib.import_module(f"devlead.{mod_name}")
            rows.append(f'<tr><td><code>devlead.{mod_name}</code></td><td class="pass">IMPORTS OK</td></tr>')
        except Exception as e:
            rows.append(f'<tr><td><code>devlead.{mod_name}</code></td><td class="fail">IMPORT FAILED: {_esc(str(e)[:80])}</td></tr>')

    return f"""<h2>6. Module health</h2>
<p>Can every Python module import without errors?</p>
<table><thead><tr><th>Module</th><th>Status</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table>"""


def _check_files_changed(repo_root: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "diff", "--stat", "HEAD"],
            capture_output=True, text=True, timeout=10, cwd=str(repo_root),
        )
        if result.returncode != 0:
            result = subprocess.run(
                ["git", "status", "--short"],
                capture_output=True, text=True, timeout=10, cwd=str(repo_root),
            )
        output = result.stdout.strip()
        if not output:
            output = "(no uncommitted changes)"
        return f"""<h2>7. Uncommitted changes</h2>
<p>What has changed since the last commit?</p>
<pre>{_esc(output)}</pre>"""
    except Exception as e:
        return f'<h2>7. Uncommitted changes</h2><p class="warn">Could not run git: {_esc(str(e))}</p>'


def write_report(repo_root: Path) -> Path:
    """Generate the report and write it to docs/."""
    repo_root = Path(repo_root).resolve()
    html = generate(repo_root)
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    docs_dir = repo_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    out_path = docs_dir / f"session-report-{date}.html"
    out_path.write_text(html, encoding="utf-8")
    return out_path


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
