"""Auto-generate _resume.md from real project state. Not Claude's opinion.

_resume.md is the first file every LLM reads at session start. If Claude
writes it by hand, it's just Claude talking to itself. DevLead must generate
it from actual data: intake status, audit log, git state.

Called by `devlead report` and `devlead resume` to keep the bootstrap
cursor honest.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path


def generate(repo_root: Path) -> str:
    """Build _resume.md content from real project state."""
    repo_root = Path(repo_root).resolve()
    docs_dir = repo_root / "devlead_docs"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# _resume.md",
        "",
        f"<!-- Auto-generated by DevLead at {now}. Do not hand-edit. -->",
        "",
    ]

    lines.append("## Current focus")
    lines.append("")
    focus_lines = _get_focus(docs_dir)
    lines.extend(focus_lines)
    lines.append("")

    lines.append("## Read at session start")
    lines.append("")
    lines.append("1. `devlead_docs/_resume.md` (this file)")
    lines.append("2. `devlead_docs/_intake_*.md` — scan for `status: in_progress`")
    lines.append("3. `devlead_docs/_aware_features.md` + `_aware_design.md`")
    lines.append("4. `devlead_docs/_scratchpad.md`")
    lines.append("5. `devlead_docs/_living_decisions.md`")
    lines.append("")

    lines.append("## Intake summary")
    lines.append("")
    intake_lines = _get_intake_summary(docs_dir)
    lines.extend(intake_lines)
    lines.append("")

    lines.append("## Last 5 audit events")
    lines.append("")
    audit_lines = _get_recent_audit(docs_dir)
    lines.extend(audit_lines)
    lines.append("")

    lines.append("## Uncommitted changes")
    lines.append("")
    git_lines = _get_git_status(repo_root)
    lines.extend(git_lines)
    lines.append("")

    lines.append("## Hierarchy convergence")
    lines.append("")
    hierarchy_lines = _get_hierarchy(docs_dir)
    lines.extend(hierarchy_lines)
    lines.append("")

    lines.append("## Next TTOs to implement")
    lines.append("")
    next_lines = _get_next_ttos(docs_dir)
    lines.extend(next_lines)
    lines.append("")

    lines.append("## Plan file")
    lines.append("")
    plan_lines = _get_plan_pointer()
    lines.extend(plan_lines)
    lines.append("")

    return "\n".join(lines)


def refresh(repo_root: Path) -> Path:
    """Regenerate _resume.md and write it to disk."""
    repo_root = Path(repo_root).resolve()
    docs_dir = repo_root / "devlead_docs"
    content = generate(repo_root)
    out = docs_dir / "_resume.md"
    out.write_text(content, encoding="utf-8")
    return out


def _get_focus(docs_dir: Path) -> list[str]:
    try:
        from devlead import intake
        in_progress = intake.list_by_status(docs_dir, "in_progress")
        if not in_progress:
            return ["No active focus. Run `/devlead focus <intake-id>` to set one."]
        lines = []
        for entry, path in in_progress:
            lines.append(f"- **{entry.id}** — {entry.title} [{path.name}]")
        return lines
    except Exception as e:
        return [f"(error reading intake: {e})"]


def _get_intake_summary(docs_dir: Path) -> list[str]:
    try:
        from devlead import intake
        done = 0
        in_progress = 0
        pending = 0
        entries_by_status: dict[str, list[str]] = {"in_progress": [], "pending": [], "done": []}
        for f in sorted(docs_dir.glob("_intake_*.md")):
            for e in intake.read(f):
                if e.status == "done":
                    done += 1
                elif e.status == "in_progress":
                    in_progress += 1
                    entries_by_status["in_progress"].append(f"{e.id}: {e.title}")
                else:
                    pending += 1
                    entries_by_status["pending"].append(f"{e.id}: {e.title}")

        lines = [f"{done} done, {in_progress} in progress, {pending} pending."]
        if entries_by_status["in_progress"]:
            lines.append("")
            lines.append("**In progress:**")
            for e in entries_by_status["in_progress"]:
                lines.append(f"- {e}")
        if entries_by_status["pending"]:
            lines.append("")
            lines.append("**Pending:**")
            for e in entries_by_status["pending"]:
                lines.append(f"- {e}")
        return lines
    except Exception as e:
        return [f"(error: {e})"]


def _get_recent_audit(docs_dir: Path) -> list[str]:
    try:
        from devlead import audit
        events = audit.tail(docs_dir, 5)
        if not events:
            return ["(no audit events)"]
        lines = []
        for ev in events:
            ts = ev.get("ts", "?")
            event = ev.get("event", "?")
            result = ev.get("result", "")
            detail = ev.get("intake_id", ev.get("file", ev.get("message", "")))
            lines.append(f"- `{ts}` **{event}** {result} {detail}")
        return lines
    except Exception as e:
        return [f"(error: {e})"]


def _get_hierarchy(docs_dir: Path) -> list[str]:
    try:
        from devlead import hierarchy
        h_path = docs_dir / "_project_hierarchy.md"
        if not h_path.exists():
            return ["(no _project_hierarchy.md)"]
        sprints = hierarchy.parse(h_path)
        return hierarchy.summary(sprints).splitlines()
    except Exception as e:
        return [f"(error: {e})"]


def _get_next_ttos(docs_dir: Path) -> list[str]:
    try:
        from devlead import hierarchy
        h_path = docs_dir / "_project_hierarchy.md"
        if not h_path.exists():
            return ["(no hierarchy)"]
        sprints = hierarchy.parse(h_path)
        todos = []
        for s in sprints:
            for bo in s.bos:
                for tbo in bo.tbos:
                    for tto in tbo.ttos:
                        if not tto.done:
                            todos.append(f"- [ ] {tto.id}: {tto.name} (under {tbo.id} / {bo.id})")
        return todos if todos else ["All TTOs complete."]
    except Exception as e:
        return [f"(error: {e})"]


def _get_plan_pointer() -> list[str]:
    import glob
    plans = sorted(glob.glob(str(Path.home() / ".claude" / "plans" / "*.md")))
    if not plans:
        return ["(no plan files found)"]
    latest = plans[-1]
    return [f"Latest plan: `{latest}`", "Read this before starting implementation."]


def _get_git_status(repo_root: Path) -> list[str]:
    try:
        result = subprocess.run(
            ["git", "status", "--short"],
            capture_output=True, text=True, timeout=10,
            cwd=str(repo_root),
        )
        output = result.stdout.strip()
        if not output:
            return ["Clean — no uncommitted changes."]
        file_count = len(output.splitlines())
        return [f"{file_count} uncommitted files.", "", "```", output[:500], "```"]
    except Exception:
        return ["(could not run git)"]
